### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by akwsa** [ardiansyah/laravel-starter#1]
vagrant@homestead:~/Code/laravel_sm$ composer update

> php artisan clear-compiled

  [ErrorException]
  Class 'Cornford\Setter\Facades\Setting' not found

Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

  [RuntimeException]
  Error Output:

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

 What Should i do with that error?

**Comment by ardiansyah** [comment]
Please run composer update again.

It should work.
